HW1 repush
ok-technopolis-autumn-2022/Porublev_Egor pull request #1
Opened 2022-10-03 10:48 UTC by FullFool03

переделал полностью репозиторий потому что в старом все закомитил сам сразу и не понял как откатить и не удалил еще весь js и css код пожалуйста не обращайте на него внимания я потом уберу.

2022-10-03 11:07 UTC, fromanywhere requested changes
Нужно добавить больше семантики и почистить лишнее

2022-10-03 11:07 UTC, fromanywhere commented on TODO.html
> +            <input type="button" name="select-all.png">
Зачем здесь name?

2022-10-03 11:07 UTC, fromanywhere commented on TODO.html
> +                <input id="Html"
Зачем здесь id и name?

2022-10-03 11:07 UTC, fromanywhere commented on TODO.html
> +        <div class="tasks" id="tasks">
Здесь лучше использовать другой тег

2022-10-03 11:07 UTC, fromanywhere commented on TODO.html
> +            <span class="right"> Clear completed </span>
Сюда тоже можно нажать

2022-10-03 14:55 UTC, FullFool03 commented on TODO.html
> +                <input id="Html"
я пытался реализовать удаление и нашел его только через getElementById('task1') поэтому и натыкал там везде id и name

2022-10-03 14:56 UTC, FullFool03 commented on TODO.html
> +        <div class="tasks" id="tasks">
вместо div в tasks ? что то типа как attic ?

2022-10-03 14:57 UTC, FullFool03 commented on TODO.html
> +            <span class="right"> Clear completed </span>
понял спасибо

2022-10-03 15:23 UTC, fromanywhere commented on TODO.html
> +        <div class="tasks" id="tasks">
здесь должен быть список

2022-10-03 15:23 UTC, fromanywhere commented on TODO.html
> +                <input id="Html"
Это выходит за рамки этого ДЗ

2022-10-07 08:00 UTC, FullFool03 commented on TODO.html
> +                <input id="Html"
убрал

2022-10-07 08:01 UTC, FullFool03 commented on TODO.html
> +            <input type="button" name="select-all.png">
переделал, лишние имена убрал

2022-10-07 08:01 UTC, FullFool03 commented on TODO.html
> +        <div class="tasks" id="tasks">
сделал список

2022-10-07 12:22 UTC, fromanywhere requested changes

2022-10-07 12:22 UTC, fromanywhere commented on TODO.html
> +            <span class="todo-app_footer buttons">
здесь тоже нужно подумать про role и aria-label — нужно описать группу радиокнопок

2022-10-07 12:22 UTC, fromanywhere commented on main.css
> +h1 {
оставьте это на вторую домашку, тут всё равно всё неправильно

2022-10-07 12:22 UTC, fromanywhere commented on main.js
> +function Remove() {
а это на ноябрь

2022-10-07 13:01 UTC, FullFool03 commented on main.css
> +h1 {
Говорили же что если все сделано можно начать тыкать css. У меня кроме role и aria label в кнопках внизу что то ещё нужно исправить ?

2022-10-07 13:01 UTC, FullFool03 commented on main.css
> +h1 {
Говорили же что если все сделано можно начать тыкать css. У меня кроме role и aria label в кнопках внизу что то ещё нужно исправить ?

2022-10-07 13:01 UTC, FullFool03 commented on main.js
> +function Remove() {
Да я уже понял что трогать JS не надо, я удалю сегодня все оттуда.

2022-10-07 13:28 UTC, fromanywhere approved these changes

2022-10-07 13:28 UTC, fromanywhere commented on main.css
> +h1 {
говорили, что это идет во второй домашке, которую лучше начинать, когда первую сдадите

2022-10-07 14:08 UTC, merged